### ISSUE TITLE
What does C_Ratio means?

### ISSUE THREAD

**Issue by wisdomGEsLA** [ml-postech/TTEN#1]
Hi! very happy to see such a simple and practical method for mitigating popularity bias.

I'm wondering what does C_Ratio means in main.py? Is it the Frequency Ratio in Fig.1(a) in the paper?

**Comment by dain5832** [comment]
Hi!
You're right, C_ratio in main.py refers to the frequency ratio within each popularity group, as shown in Fig 1(a).

The variable name C_Ratio comes from the paper 'Co-training Disentangled Domain Adaptation Network for
Leveraging Popularity Bias in Recommenders [SIGIR 22]'. However, to avoid confusion, we should consider changing it to something more precise, like "group_freq_ratio".

Thanks for pointing out!

**Comment by wisdomGEsLA** [comment]
Thank you for your reply! Could you tell me which of the two lines of code in _main.py_ gets the data in Fig.1 (b)? I think it seems to be the second line, is it correct?
```
print('Item popularity:', np.round(recall_lst_i/all_user_num, 4), np.round(ndcg_lst_i/item_grp_num, 4))
print('Item_popularity:', np.round(hit_lst_i/test_item_num_lst_i, 4))
```

**Comment by dain5832** [comment]
No problem!
Fig.1 (b) shows the recall@20 for each popularity group, so the first line  np.round(recall_lst_i/all_user_num, 4) gets the result.

**Comment by wisdomGEsLA** [comment]
> No problem! Fig.1 (b) shows the recall@20 for each popularity group, so the first line np.round(recall_lst_i/all_user_num, 4) gets the result.

Thank you for your answer! After running LGN (SSM) on Gowalla, I feel that the second line is more in line with the data in Figure 1b. Did I make a mistake while running the code?
```
Item popularity: [0.0102 0.0152 0.0165 0.0163 0.0093][0.0067 0.0893 0.0115 0.0143 0.0199]
Item_popularity: [0.018 0.0257 0.0416 0.0622 0.1157]
```
The following are the commands I use to run the code:
_python main.py --dataset fair_gowalla --lr 0.001 --model LGN --loss_type ssm_

**Comment by dain5832** [comment]
Ohh sorry my bad, you're right.
As recall refers to the (# of correct items)/(# of total items), we used the second line to measure the group recall.
